---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero
  require_chef_omnibus: 13
  always_update_cookbooks: true

platforms:
  - name: macosx-10.12
    driver:
      customize:
        cpus: 2
  - name: macosx-10.13
    driver:
      customize:
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[xcode-tests::default]
    verifier:
      inspec_tests:
        - test/recipes
